services:
  - type: web
    name: materialhub-web
    env: python
    plan: free
    branch: main
    buildCommand: './build.sh'
    startCommand: rosemary db:setup -y && gunicorn app:app --bind 0.0.0.0:$PORT

    envVars:
      - key: FLASK_ENV
        value: production

      - key: FLASK_APP_NAME
        value: MaterialsHub

      - key: DOMAIN
        value: materialhub-web.onrender.com

      - key: SECRET_KEY
        sync: false

      - key: DATABASE_URL
        fromDatabase:
          name: materialhub-db
          property: connectionString

databases:
  - name: materialhub-db
    plan: free
    databaseName: materialhub
    user: materialhub_user
    password: materialhub_password
